### ISSUE TITLE
Multiple proxy clients for different domains on different servers

### ISSUE THREAD

**Issue by joelwurtz** [FriendsOfSymfony/FOSHttpCacheBundle#115]
I have a sf2 site which deal with multiple sub domains (i.e. `www.site` and `admin.site`) and i need to handle cache on both of this subdomain which are handle by varnish.

But configuration of the proxy_client only allow to pass one domain, i was thinking of creating a PR to use factory for the proxy client (but it will certainly be BC) so instead of having this : 

```
proxy_client:
    varnish:
        servers: 127.0.0.1
        base_url: www.site
```

We can have something like this

```
proxy_client:
    www_proxy:
        type: varnish
        servers: 127.0.0.1
        base_url: www.site
    admin_proxy:
        type: varnish
        servers: 127.0.0.1
        base_url: admin.site
```

(We maybe can avoid BC by saying that if no type is defined we use the name of proxy as the type)

Let me know what you think, or if there is a better way to handle this use case, thanks !
