### ISSUE TITLE
flashes cookie not working in chrome

### ISSUE THREAD

**Issue by purplefish32** [FriendsOfSymfony/FOSHttpCacheBundle#210]
The flashes cookie is being generated in firefox but not in chrome. (41.0.2272.76 Ubuntu 14.04 (64-bit))

```` yaml
#config.yml
fos_http_cache:
    cache_manager:
        enabled: %cache_manager_enabled%
    proxy_client:
        varnish:
            servers: %varnish_servers%
            base_url: %base_url%
    user_context:
        enabled: true
        role_provider: true
    flash_message:
        enabled: true
        name: flashes
        path: /
        host: %base_url%
        secure: debug
````

**Comment by purplefish32** [comment]
Hmmm, 
Removed : 

````yaml
path: /
        host: %base_url%
        secure: debug
````

Works now, sorry
