### ISSUE TITLE
TagManager service?

### ISSUE THREAD

**Issue by stevenmusumeche** [FriendsOfSymfony/FOSHttpCacheBundle#213]
Is there a way to get the TagHandler service to use in commands?  For example:

```
$tagHandler = $this->getContainer()->get('tag_handler_service_name');
$tagHandler->invalidateTags(array('test'));
```
The documentation shows this:

`$tagHandler = $this->getContainer()->get('fos_http_cache.handler.tag_handler');`

However, I get this error:

`You have requested a non-existent service "fos_http_cache.handler.tag_handler".`

Here is my config:

```
fos_http_cache:
    tags:
        enabled: true
    proxy_client:
        varnish:
            servers: 5.5.5.5
    cache_manager:
        enabled: true
        generate_url_type: false
```
