### ISSUE TITLE
Login redirect infinite loop

### ISSUE THREAD

**Issue by purplefish32** [FriendsOfSymfony/FOSHttpCacheBundle#227]
Hello, 
I am getting a dreaded login ininite loop error, and have been scratching my head for over a week to pin-point. 

I am using both FOSUserBundle and FOSHttpCacheBundle on a loadbalanced varnish setup with the following security.yml : 

````yaml
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider:       fos_userbundle
                csrf_provider:  form.csrf_provider
                check_path:     fos_user_security_check
                login_path:     /login
                default_target_path: /opened-sessions
                always_use_default_target_path: true
                use_referer:                    false

            logout:
                path:        fos_user_security_logout
                target:      /
                invalidate_session: true
                handlers:
                   - fos_http_cache.user_context.logout_handler
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
````

Are there any docs on how to setup both  FOSUserBundle and FOSHttpCacheBundle together ?

Please help me, is I am going insane ;)

**Comment by ddeboer** [comment]
> a dreaded login ininite loop error

What exactly do you mean by infinite loop; that submitting the login page returns you to the login page itself, without any error messages, so a cached version of it? 

> Are there any docs on how to setup both FOSUserBundle and FOSHttpCacheBundle together ?

The [http://foshttpcachebundle.readthedocs.org/en/latest/] refer frequently to the library docs and vice versa. We have no dedicated docs for the combination of bundle and lib, as that would involve quite some duplication. If you just use the Symfony configuration for the bundle, you won’t have to mind the underlying library too much. What are you missing in the docs?

**Comment by purplefish32** [comment]
My app works fine if I bypass Varnish or run the app localy. I can login OK, but as soon as I logout I get an infinite loop on my /login route.

If I delete all cookies and refresh the page It works once more. So I am guessing that cookies are not properly deleted on logout.

Basicly,any time I have a PHPSESSID cookie on the login page, it loops

I forgot to supply the config.xml

````yml
fos_http_cache:
    debug:
        enabled: true
    cache_manager:
        enabled: %cache_manager_enabled%
    proxy_client:
        varnish:
            servers: %varnish_servers%
            base_url: %base_url%
    user_context:
        role_provider: true
    flash_message:
        enabled: true
        name: flashes
    cache_control :
        rules:
            -
                match:
                    path: ^/login
                headers:
                    cache_control:
                        public: false
                        max_age: 0
                        s_maxage: 0
            -
                match:
                    path: ^/
                headers:
                    cache_control:
                        public: true
                        max_age: 120
                        s_maxage: 120
````

I can allso supply some of the VCL if needed
 
You can see the loop on this test site : http://self3.innovalangues.net/login
On first page load it shows the page, if you refresh it loops.

The documentation i am following is this one : http://foshttpcachebundle.readthedocs.org/en/latest/reference/configuration/headers.html?highlight=login

But the example is a subdomain, and I am not sure how to convert it to a "standard" FOSUserBundle login route

**Comment by ddeboer** [comment]
Can you try to add `overwrite: true`, as shown in the docs? And looking at [FOSUserBundle’s routes](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/config/routing/security.xml), you may also want to add the `/logout` path, so something like: `^/login|logout`.

**Comment by purplefish32** [comment]
I have update the config file : 

````yaml
    cache_control :
        defaults:
            overwrite: false
        rules:
            -
                match:
                    path: ^/login|logout
                headers:
                    overwrite: true
                    cache_control:
                        public: false
                        max_age: 0
                        s_maxage: 0
            -
                match:
                    path: ^/
                headers:
                    cache_control:
                        public: true
                        max_age: 120
                        s_maxage: 120
````

I have purged symfony caches and restarted Varnish, still no luck.
Is there something that could be wrong with the VCL ?
