### ISSUE TITLE
Invalidate all variants of a route

### ISSUE THREAD

**Issue by benr77** [FriendsOfSymfony/FOSHttpCacheBundle#253]
Hi,

I'm using the Symfony cache, and configuration yml to set things up. I have a route, `blog_edit` which need to invalidate a different route `list_show`. However, `list_show` accepts parameters - i.e. `/lists/{listId}/show` is the path.

Is it possible to set up the `blog_edit` route to invalidate ALL routes belonging to the `list_show` route i.e. `/lists/1/show` and `/lists/2/show` and `/lists/3/show` and `/lists/4/show` and so on???

My current config is

```
  invalidation:
    rules:
      -
        match:
          attributes:
            _route: ^blog_edit$
        routes:
          list_show: ~
```
However this does not appear to be invalidating any `list_show` route at all.

Thanks
