### ISSUE TITLE
Issue with FOSRestBundle

### ISSUE THREAD

**Issue by nicolasmure** [FriendsOfSymfony/FOSHttpCacheBundle#277]
Hi,

Thank you for this bundle!
I'm building an app with an admin panel (html) and a REST API (json). I have FOSRestBundle installed. I wanted to add FOSHttpCacheBundle to control Varnish 3.0.7 cache so I followed [the doc](http://foshttpcachebundle.readthedocs.org/en/latest/index.html) : [varnish config](http://foshttpcache.readthedocs.org/en/stable/varnish-configuration.html), [caching headers](http://foshttpcachebundle.readthedocs.org/en/latest/features/headers.html), [user context](http://foshttpcachebundle.readthedocs.org/en/latest/features/user-context.html).

Here is my config for `fos_http_cache` :
```yaml
fos_http_cache:
    proxy_client:
        varnish:
            servers: %myapp_trusted_proxies%
            base_url: myapp.com
    user_context:
        enabled: true
        hash_cache_ttl: 600
    cache_control:
        defaults:
            overwrite: true
        rules:
            # match everything to set defaults
            -
                match:
                    path: ^/
                headers:
                    overwrite: false
                    cache_control: { public: true, max_age: 600, s_maxage: 600 }
                    etag: true

```
When I try to access `myapp.com` with a browser, I get the following error :
`406 Not Acceptable - No matching accepted Response format could be determined` thrown from `FOS\RestBundle\EventListener\FormatListener l.67`.
I have this error since I configured my varnish 3 to support user_context ([as explained in the doc](http://foshttpcache.readthedocs.org/en/stable/varnish-configuration.html#user-context)).
Apparently, the reverse-proxy is sending a request with a accept header to `application/vnd.fos.user-context-hash`, which is disturbing FOSRestBundle who's trying to determine the response format type from that header.
When I change my `fos_rest` config as it :
```yaml
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    body_converter:
        enabled: true
    view:
        view_response_listener: 'force'
        # When I add these 2 lines :
        mime_types:
            html: ['application/vnd.fos.user-context-hash']

    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: ['html', 'text/css'], fallback_format: text/plain }
```
the request to `myapp.com` doesn't throw an error, but asks me to save the content of this page as an html file. I know this is not what I should do, but it might help to understand where the problem comes from.

What am I doing wrong ? How to make FOSHttpCacheBundle and FOSRestBundle work together ?
Thanks for your help :smile: !

**Comment by dbu** [comment]
i think you have to solve this on the FOSRestBundle side. does the `format_listener` allow you to exclude some paths from validating? otherwise you could add an excplicit rule for the user context hash path and allow the application/vnd.fos.user-context-hash for that path. (i guess the rules are processed in order, so you need to put it above the one for `^/`.)

**Comment by nicolasmure** [comment]
thanks @dbu for your answer!
I've already tried to add `application/vnd.fos.user-context-hash` to the `priorities` array of the `^/` rule, but it doesn't work.
I've added the following rule at the top of rules array :
```yaml
{ path: '^/_fos_user_context_hash', priorities: ['application/vnd.fos.user-context-hash', 'html', 'text/css'], fallback_format: text/plain }
```
but it doesn't work neither (even without `html` and `text/css` in the `priorities` array).

Of course, removing all the rules is working... I'll try to work with [FOSRestBundle listeners](http://symfony.com/doc/current/bundles/FOSRestBundle/3-listener-support.html) to make cache work without breaking my API.


On the other hand, I'm facing an other issue when I try to login : I can fill up the login form but I get stuck on `/login_check` with a 500 error `You must configure the check path to be handled by the firewall using form_login in your security firewall configuration.` from `FOS\UserBundle\Controller\SecurityController l.69`.
This issue has appeared since I've installed varnish (and just varnish, not the FOSHttpCacheBundle).
If I by-pass caching, I don't have the problem :
```vcl
sub vcl_recv {
    if (req.http.host ~ "myapp.com" )
    {
        return (pass);
    }
}
```
but of course, it's not what I want. Do you have any clues on this ?

**Comment by nicolasmure** [comment]
OK, I found a workaround for my `format_listener` problem. I have to keep the rules I currently use, so I decided to adapt the service used as the format listener :
```yaml
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    body_converter:
        enabled: true
    view:
        view_response_listener: 'force'

    format_listener:
        enabled: true
        service: my_app.format_listener_adapter # <== here's the trick
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: ['html', 'text/css'], fallback_format: text/plain }
```
The corresponding class : 
```php
namespace MyApp\MyBundle\EventListener;

use FOS\RestBundle\EventListener\FormatListener;
use Symfony\Component\HttpKernel\Event\GetResponseEvent;
use Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException;

/**
 * Adapter of the FOSRest FormatListener for the FOSHttpCache's user_context.
 */
class FormatListenerAdapter
{
    /**
     * Base FormatListener
     * @var FormatListener
     */
    private $formatListener;

    /**
     * Constructor.
     *
     * @param FormatListener $formatListener
     */
    public function __construct(FormatListener $formatListener)
    {
        $this->formatListener = $formatListener;
    }

    /**
     * Determines and sets the Request format by calling
     * the base FormatListener.
     * Catches the exception thown by the base FormatListener
     * when processing the user_context_hash request for the cache.
     *
     * @param GetResponseEvent $event The event
     *
     * @throws NotAcceptableHttpException
     */
    public function onKernelRequest(GetResponseEvent $event)
    {
        try {
            $this->formatListener->onKernelRequest($event);
        } catch (NotAcceptableHttpException $e) {
            if ($event->getRequest()->getPathInfo() != '/_fos_user_context_hash') {
                throw $e;
            }
        }
    }
}
```
and the service definition : 
```xml
<service id="my_app.format_listener_adapter" class="MyApp\MyBundle\EventListener\FormatListenerAdapter">
    <tag name="kernel.event_listener" event="kernel.request" method="onKernelRequest" priority="34" />
    <argument type="service" id="fos_rest.format_listener" />
</service>
```
As you can see, I'm catching the `NotAcceptableHttpException` thrown by the base format listener service for the `/_fos_user_context_hash` request.
Not very sexy, but it does the trick... What do you think of it ?

**Comment by nicolasmure** [comment]
I'm closing the issue for now, I'm gonna use the solution I posted above.
I'm gonna make an other issue for my other problem (500 error on `/login_check`).

Thanks for your help!

See you :rabbit: !

**Comment by nicolasmure** [comment]
I also solved my 500 error today on `/login_check` after login form submit by adding this at the end of my `vcl_recv` function (varnish 3.0.7) : 
```vcl
if (req.request != "GET" && req.request != "HEAD") {
    return (pass);
} else {
    return (lookup);
}
```
hope it could help :wink:

**Comment by dbu** [comment]
the POST problem looks indeed like you missed something in your VCL. usually you don't take the decision to `lookup` yourself, but let the default VCL do that (if you don't return in your vcl_recv, the default vcl_recv is executed after yours and makes the decision. it already has this logic for what request methods might be cached or not). https://github.com/FriendsOfSymfony/FOSHttpCache/tree/master/tests/Functional/Fixtures/varnish-3 contains the vcl files we use for testing, if you want to have some inspiration.

the other issue sounds like there is some problem with FOSRestBundle - if you want to get rid of your hack, you should ask over at the FOSRestBundle, i am no expert on that one.

**Comment by nicolasmure** [comment]
thank you @dbu for your explanation!

**Comment by ixarlie** [comment]
@nicolasmure if you are using FOSRest >= 1.5 you can use
```yml
format_listener:
  rules:
    - { path: '^/_fos_user_context_hash', stop: true }
```

http://symfony.com/doc/current/bundles/FOSRestBundle/format_listener.html#disabling-the-format-listener-via-rules
