### ISSUE TITLE
cache header rule configuration cleanup

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCacheBundle#35]
currently, we have a ton of match criteria for the rules mixed up with the header configuration in case this matches.

```
path: ^/$
host: ^login.example.com$
methods: [ GET, HEAD ]
unless_role: ROLE_NO_CACHE
...
controls: { public: false, max_age: 0, s_maxage: 0, last_modified: "-1 hour" }
vary: [Accept-Encoding, Accept-Language]
```

we maybe should group this:

```
match:
    path: ^/$
    host: ^login.example.com$
    methods: [ GET, HEAD ]
    unless_role: ROLE_NO_CACHE
    ...
controls: { public: false, max_age: 0, s_maxage: 0, last_modified: "-1 hour" }
vary: [Accept-Encoding, Accept-Language]
```

possibly with the option to specify just the path outside of the match and validation in configuration that you have exactly one of `match` or a `path` specified.

see also #33
