### ISSUE TITLE
X-User-Context-Hash header is not set

### ISSUE THREAD

**Issue by spointecker** [FriendsOfSymfony/FOSHttpCacheBundle#371]
Hi,

I am trying to implement the cache only for logged out users but I have some problems getting there.
First of all: Is there a full example of implementing such a setting?

I never have a `X-User-Context-Hash` header in my response. Also if I use the role provider. (I cleared the caches every time I changed the config)

My setting so far:
- Using v2.0.*
- Implemented custom context `IsAuthenticatedProvider`
- Added the provider to my service configuration
- Extended the `security.yml` like the documentation said (added `_fos_user_context_hash` to access control)
- Added `RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]` to my `.htaccess`
- Current config:
```
fos_http_cache:
    user_context:
        hash_cache_ttl: 3600
        enabled: true

    cache_control:
        defaults:
            overwrite: true

        rules:
            # match index
            -
                match:
                    path: ^/$
                headers:
                    cache_control: { public: true, private: false, max_age: 86400, s_maxage: 86400 }
                    etag: true
```
One more thing: I have also a problem with the authentication context in my custom context provider:
If I want to check if the user is logged in (like in the documentation) it says, that there is no authentication token set -> but I added the access rule like in the documentation said (see http://foshttpcachebundle.readthedocs.io/en/stable/features/user-context.html) 
but even if I just set a random value for the context like this, the header is missing.
```
public function updateUserContext(UserContext $userContext)
    {
        $userContext->addParameter('authenticated', 'test');
    }
```
