### ISSUE TITLE
Missing `vary`header with Symfony proxy client

### ISSUE THREAD

**Issue by thomas-dotworx** [FriendsOfSymfony/FOSHttpCacheBundle#399]
We are currently using the Symfony proxy client and from time to time the `vary` header is missing in the response headers. This occurs very randomly and I can't find the reason for the header disappearing. Could you help us with that issue?

Here's an example response:

**age**:2085
**cache-control**:max-age=0, no-cache, public, s-maxage=86400
**content-length**:77264
**content-type**:text/html; charset=UTF-8
**date**:Thu, 09 Nov 2017 10:45:04 GMT
...
**status**:200
**strict-transport-security**:max-age=31536000; includeSubDomains

Our config:
```
fos_http_cache:
    flash_message:
        enabled: true
        secure: true
        name: flashes
        path: /

    user_context:
        hash_cache_ttl: 600
        role_provider: true

    proxy_client:
        symfony:
            http:
                servers:
                    - 127.0.0.1
```
