### ISSUE TITLE
Invalidation rules not triggered when configured with yml based configurations

### ISSUE THREAD

**Issue by ranjzith** [FriendsOfSymfony/FOSHttpCacheBundle#479]
Hi all,

I am using Varnish 4.1.10 as the http accelerator along with Symfony 3.4.13 and PHP 7.1.16 in backend application and would like to use FOSHttpCacheBundle to handle cache invalidation. I tried setting up the invalidation rules as mentioned below(used ^2.4@dev in my composer.json), but could not see any incoming requests in varnish for purge. 

config.yml
```
fos_http_cache:
  cache_manager:
    enabled: true
  proxy_client:
    varnish:
      tags_header: My-Cache-Tags
      tag_mode: ban
      header_length: 1234
      default_ban_headers:
        Foo: Bar
      http:
        servers:
          - localhost:6081
        base_url: development.local:6081
  invalidation:
    enabled: true
    rules:
      -
        match:
          attributes:
            _route: "my_edit_page"
        routes:
          my_view_page: ~
```

Also I am able to invalidate the route when used as below,
```
$cacheManager = $this->getContainer()->get('fos_http_cache.cache_manager');
$cacheManager->invalidateRoute('my_view_page')->flush();

```
In the above sample my route resolves to a GET request and the response status code is 200.
While debugging, I found that FOS\HttpCacheBundle\Http\RuleMatcher is actually initialized with FOS\HttpCacheBundle\Http\RequestMatcher\UnsafeRequestMatcher, which inturn returning false from RuleMatcher's matches() method call and skipping the invalidation process (please correct me if my understanding is wrong), observed stack trace below,
```
UnsafeRequestMatcher->matches()
$this->requestMatcher && !$this->requestMatcher->matches($request)
RuleMatcher->matches()
$this->mustInvalidateRule->matches($request, $response)
InvalidationListener->onKernelTerminate()
```
I also see a CacheableRequestMatcher, which might solve my problem if replaced for UnsafeRequestMatcher in matcher.xml. 
Any lead on this would be a great help!!

Thanks!
