### ISSUE TITLE
Response tags were set even tags.enabled is set to false

### ISSUE THREAD

**Issue by ranjzith** [FriendsOfSymfony/FOSHttpCacheBundle#507]
Hi Team,

I have been using foshttpcache bundle with varnish 4 and symfony 3.4. Recently when I disabled varnish for some reason, I still see fos bundle trying to connect to varnish server on log-in and log-out, and the responses are still tagged as specified in config.yml, is this behavior expected. It seems like the enabled property is not considered for foshttpcache bundle operations. Please clarify me on this, here is config.yml entry for foshttpcache bundle (here the injected property varnish_enabled is set to false)

```
fos_http_cache:
  user_context:
    enabled: %varnish_enabled%
    user_identifier_headers:
      - Cookie
      - Authorization
      - X-Fos-Original-Url
    hash_cache_ttl: 0
    logout_handler:
      enabled: %varnish_enabled%
  cache_manager:
    enabled: true
  tags:
    expression_language: my.expression_language
    enabled: %varnish_enabled%
    rules:
      -
        match:
          path: ^/myURL$
        tag_expressions: ["myTag-'~myId"]
  proxy_client:
    default: varnish
    varnish:
      tags_header: xkey-purge
      tag_mode: purgekeys
      header_length: 7500
      http:
        servers:
          - %fos_varnish_http_server%
        base_url: %fos_varnish_base_uri%
  invalidation:
    enabled: %varnish_enabled%
```
