### ISSUE TITLE
Env var in configuration will throw an error

### ISSUE THREAD

**Issue by tft7000** [FriendsOfSymfony/FOSHttpCacheBundle#521]
I use this bundle in version 2.6.1 under symfony 4.2.7. I have different environments: a local dev environment with one varnish, different test environments and a production environment with several varnish services.

I want an independant fos_http_cache.proxy_client.varnish.http configuration for each of those environments. So I want to set different servers and base_url.

If I do that using env vars, I get an execption.
```
parameters:
  env(VARNISH_HTTP): '{ "servers": ["varnish1.test"], "base_url": "site.test" }'

fos_http_cache:
    proxy_client:
        varnish:
            http: '%env(json:VARNISH_HTTP)%'
```
Will produce 
> The "http.servers" section must be defined for the proxy "varnish"
in `Configuration.php line 495`

if I look at `$config` in `Configuration.php:495` it looks like this:
```
array (
  'varnish' =>
  array (
    'http' => 'env_0b2794b52dbf3f2c_json_VARNISH_HTTP_aab919abe2c77c3cbf24f764530d3948',
    'tag_mode' => 'ban',
  ),
)
```

I don't know, how the new configuration system with .env is working. I assume the validation cannot be at compile time, as the environment variable is loaded at runtime.

I tried just replacing servers, but I get the same result.
If I replace the single strings it works, however it feels strange to have to define eg 3 varnish servers on every environment, as I cannot add an additional service in an environment without updating all environments.

Is this a bug or a configuration mistake on my side?
Is there a fix or a workaround?

**Comment by dbu** [comment]
i have a vague recollection to have seen a similar problem before, but can't find it unfortunately. i would expect symfony to solve that somehow, but maybe we need to adjust something in the bundle configuration validation. i don't have time to dig into it, but if you find anything, please let me know. maybe the general symfony documentation or stackoverflow know something?

**Comment by thePanz** [comment]
@tft7000 can you try to force Symfony to resolve the env variable? you should use `resolve:`.
I guess it should be something like `%env(json:resolve:VARNISH_HTTP)%'`?

**Comment by tft7000** [comment]
@thePanz : thanks - but seems not to work:
fos_http_cache.yml:
```
fos_http_cache:
    proxy_client:
        varnish:
            http: '%env(json:resolve:VARNISH_HTTP)%'
```
.env:
```
VARNISH_HTTP='{ "servers": ["127.0.0.1"], "base_url": "site.test" }'
```
result (eg if I call `bin/console` on the command line):
```
$ bin/console

In BaseNode.php line 422:

  Invalid configuration for path "fos_http_cache.proxy_client": The "http.servers" section must be defined for the proxy "varnish"


In Configuration.php line 494:

  The "http.servers" section must be defined for the proxy "varnish"
```

(I think resolve means, that parameters within the env var will get resolved)
