### ISSUE TITLE
Tag cache not created

### ISSUE THREAD

**Issue by charliefancelli** [FriendsOfSymfony/FOSHttpCacheBundle#540]
Hi,

I use this bundle with FosRestBundle with Symfony Proxy Client and Symfony Cache (before using Varnish) in a SF 4.4 project.

When i try to use InvalidateRoute or InvalidatePath all is working well.
But when i try to use `InvalidateTags` nothing is cleared.
After spent few hour to debug all the process i'm stuck. Nothing happened because in the `FilesystemTagAwareAdapter` the tag folder isn't found.

```
line 196
if (!file_exists($tagFolder = $this->getTagFolder($tagId))) {
                continue;
            }
```

I look on folders an the requested folder is not present `/var/cache/dev/http_cache/@/tags/+/.....`, no folder `tags` is here (other folders with one letter are here).

I can't understand why the folder `tags` is not created when the request is cached, the tag property is in headers 
```
x-cache-debug: 1 
 x-cache-tags: items-9eaa6717-6f8b-11ea-a0bb-0242c0a85004 
 x-content-digest: enf112aff7038b98d94706566b699ce86d47376fe4185749c0c34bfe19f0dd0b58
```

My `CacheKernel` is well configured :
```
$store = new Psr6Store([
            'cache_directory' => $kernel->getCacheDir().'/http_cache'
        ]);
        parent::__construct($kernel, $store, null, $options);
```
as my `fos_http_cache.yaml`:
```
fos_http_cache:
    proxy_client:
        symfony:
            # for single server installations:
            use_kernel_dispatcher: true
    cache_manager:
        enabled: auto
    invalidation:
        enabled: auto
    tags:
        enabled: true
    cache_control:
        defaults:
            overwrite: true
        rules:
                match:
                    path: ^/test/
                headers:
                    cache_control:
                        public: true
                        max_age: 300
                        s_maxage: 300
```

and in my Controller i use annotation :
```
@FOSCache\Tag("items", expression="'items-'~id")
```

Regards,
