### ISSUE TITLE
Revalidate rules not working

### ISSUE THREAD

**Issue by shubaivan** [FriendsOfSymfony/FOSHttpCacheBundle#542]
My qoal when I will call `app_rest_product_getproductbyid` route I need revalidate `app_rest_product_getproductbyip`api data. For set `Expires` time I jys set in in response

```
            $response
                ->setExpires($this->helper->getExpiresHttpCache());
```

I did all like in documenation and all cached like I expected. When I called first time `app_rest_product_getproductbyip` I get rwsponse and on next call time I got in `General` section contain Status Code: 200 OK (from disk cache), looks lie correct. Next I execute `app_rest_product_getproductbyid` and got data, if I correct understand in this time it should be revalidated cache for `app_rest_product_getproductbyip`. Then I expected when I call `app_rest_product_getproductbyip`  new data, but still have old data and in `General` section contain Status Code: 200 OK (from disk cache). How to revalidate cache data for another route ? Or another case how to revalidate data or change expires time for some route dependencies from event example in case when application not called, it's possible ?

One point when I got in `General` section contain Status Code: 200 OK (from disk cache) in this case my application not called, where this midllewhere where executed this magic with compare current time and expires time ? 

configure your proxy server
src/AppKernel.php

```
class AppKernel extends Kernel implements HttpCacheProvider
{
    use HttpCacheAware;

    public function __construct(string $environment, bool $debug)
    {
        parent::__construct($environment, $debug);

        $this->setHttpCache(new AppCache($this));
    }
}
```

src/AppCache.php

```
class AppCache extends HttpCache implements CacheInvalidation
{
    const TAGS_HEADER = 'Custom-Cache-Tags-Header';

    use EventDispatchingHttpCache;

    /**
     * Overwrite constructor to register event listeners for FOSHttpCache.
     */
    public function __construct(
        HttpKernelInterface $kernel,
        SurrogateInterface $surrogate = null,
        array $options = []
    ) {
        $store = new Psr6Store([
            'cache_directory' => $kernel->getCacheDir(),
            'cache_tags_header' => self::TAGS_HEADER,
        ]);

        parent::__construct($kernel, $store, $surrogate, $options);

        $this->addSubscriber(new CustomTtlListener());
        $this->addSubscriber(new PurgeListener());
        $this->addSubscriber(new RefreshListener());
        $this->addSubscriber(new UserContextListener());
        if (isset($options['debug']) && $options['debug']) {
            $this->addSubscriber(new DebugListener());
        }
    }

    /**
     * Made public to allow event listeners to do refresh operations.
     *
     * {@inheritDoc}
     */
    public function fetch(Request $request, $catch = false)
    {
        return parent::fetch($request, $catch);
    }
}
```

set up a client for your proxy server

```
$kernel = new App\AppKernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
$cacheKernel = $kernel->getHttpCache();
// Create the Symfony proxy client with KernelDispatcher
// Use $kernel, not $cacheKernel here!
$kernelDispatcher = new KernelDispatcher($kernel);
$symfony = new Symfony($kernelDispatcher);
```

one thing, without changes in `publci/index.php` http cache works like the same... Maybe I some missed and some missunderstand on configuration, could someone please me understand what excectly wrong? 

and configured fos_http_cache 

```
fos_http_cache:
  proxy_client:
    symfony:
      http:
        servers:
          - 127.0.0.1
        base_url: symfony.localhost

  cache_control:
    defaults:
      overwrite: true
    rules:
      -
        match:
          attributes: { _controller: ^App\\Controller\\Rest\\ProductController::.* }
        headers:
          cache_control:
            public: true

  invalidation:
    rules:
      -
        match:
          attributes:
            _route: "app_rest_product_getproductbyid"
        routes:
          app_rest_product_getproductbyip: ~
```

I set invalidation rules and set correct toute name, I lookked it in console debug route, but nothing not happened, calling `app_rest_product_getproductbyip` with the same expires time and the same data.

**Comment by dbu** [comment]
hi, if i understand you correctly, you are saying that your cache kernel sees a cache hit even when the expires date has been passed? according to the RFC, max-age wins over expires. do you only have expires but not a max-age?

if you only have Expires, i am not sure if the problem is within FOSHttpCache. from a quick look at the code, the decision whether a cache entry is usable or not happens in the [symfony HttpCache component](https://github.com/symfony/symfony/tree/master/src/Symfony/Component/HttpKernel/HttpCache). the FOSHttpCache only builds on top of that but does not replace the component.

**Comment by shubaivan** [comment]
@dbu problem is when I called first time  `app_rest_product_getproductbyIP` in result I set expires some time (example 12:00:00) and after when I called this rout again ny appicaction not executed and this is correct (in General section contain Status Code: 200 OK (from disk cache)).

My goal - when I will call another api,  example `app_rest_product_getproductbyID`, change expires time or revalidate data for `app_rest_product_getproductbyIP. For that I set rules

```
fos_http_cache:
   ...
 
  invalidation:
    rules:
      -
        match:
          attributes:
            _route: "app_rest_product_getproductbyid"
        routes:
          app_rest_product_getproductbyip: 
```

but nothing to happened, when I called `app_rest_product_getproductbyIP` I still got old result and my application not executed and expires time like it was before
