### ISSUE TITLE
Is ExpressionLanguage required for Symfony backend?

### ISSUE THREAD

**Issue by PabloKowalczyk** [FriendsOfSymfony/FOSHttpCacheBundle#562]
Hello,
I'm trying to configure this bundle with Symfony reverse proxy. I don't have `ExpressionLanguage` package installed.
Here is my configuration:
```
fos_http_cache:
    proxy_client:
        symfony:
            use_kernel_dispatcher: true
    tags:
        annotations:
            enabled: false
    cache_control:
        defaults:
            overwrite: true
        rules:
            -
                match:
                    path: ^/api/entities$
                headers:
                    etag: "strong"

```

This configuration gives me error:
```
php.CRITICAL: Uncaught Error: Class "Symfony\Component\ExpressionLanguage\ExpressionLanguage" not found {"exception":"[object] (Error(code: 0): Class \"Symfony\\Component\\ExpressionLanguage\\ExpressionLanguage\" not found at /var/www/html/vendor/friendsofsymfony/http-cache-bundle/src/EventListener/InvalidationListener.php:83)"}
```

Looks like `InvalidationListener` have hard dependency on `ExpressionLanguage` - is it expected behavior?
