### ISSUE TITLE
Tags invalidation not working 2 (Symfony 5.4)

### ISSUE THREAD

**Issue by ii02735** [FriendsOfSymfony/FOSHttpCacheBundle#596]
Hello,

I have the same issue when I try to invalidate a tag with the CLI, in a Symfony 5.4 project, with Symfony HttpCache.

Here is my configuration file : 

```yml
fos_http_cache:
  debug:
    enabled: true
  proxy_client:
    symfony:
      use_kernel_dispatcher: true
  cache_control:
    defaults:
      overwrite: false
    rules:
      -
        match:
          attributes: 
            _route: ^api_abilities|api_ability_by_id$
        headers:
          cache_control: { public: true, s_maxage: 2629800 }
  tags:
    enabled: true
    rules:
      - # ability 
        match:
          attributes: 
            _route: ^api_abilities$
        tags: ['abilities']

      -
        match:
          attributes: 
            _route: ^api_abilities_by_id$
        tags: ['abilities']
        tag_expressions: ["'ability-'~id"]
```

My CacheKernel class file : 

```php
class CacheKernel extends HttpCache implements CacheInvalidation
{
    use EventDispatchingHttpCache;

    /**
     * Overwrite constructor to register event listeners for FOSHttpCache.
     *
     * @param SurrogateInterface $surrogate
     * @param mixed[] $options
     */
    public function __construct(
        Kernel $kernel,
        SurrogateInterface $surrogate = null,
        array $options = []
    ) {
        $store = new Psr6Store([
            'cache_directory' => $kernel->getCacheDir()
        ]);
        parent::__construct($kernel, $store, $surrogate, $options);

        $this->addSubscriber(new PurgeListener());
        $this->addSubscriber(new RefreshListener());
        $this->addSubscriber(new UserContextListener());
        $this->addSubscriber(new PurgeTagsListener());
        $this->addSubscriber(new CleanupCacheTagsListener());
        if (isset($options['debug']) && $options['debug']) {
            $this->addSubscriber(new DebugListener());
        }
    }

    /**
     * Made public to allow event listeners to do refresh operations.
     *
     * {@inheritDoc}
     */
    public function fetch(Request $request, $catch = false)
    {
        return parent::fetch($request, $catch);
    }
}
```

And my Kernel class file : 

```php
class Kernel extends BaseKernel implements HttpCacheProvider
{
    use HttpCacheAware;
    use MicroKernelTrait;

    public function __construct(string $environment, bool $debug)
    {
        parent::__construct($environment, $debug);
        $this->setHttpCache(new CacheKernel($this));
    }
```

**The steps of my test :**

1. I call my `api_abilities` route (`/api/abilities`), and the response headers are the following : 

```http
Server: nginx/1.21.4
Content-Type: application/json
Content-Length: 89512
Connection: keep-alive
X-Powered-By: PHP/7.4.33
Set-Cookie: XDEBUG_SESSION=PHPSTORM; path=/; SameSite=Lax
Cache-Control: public, s-maxage=2629800
Date: Fri, 01 Sep 2023 16:14:18 GMT
X-Cache-Debug: 1
X-Cache-Tags: abilities
X-Content-Digest: en74cdf57df9307601a67fad384500a6fc3b1dd4be3a3f56ad1f7d74b2212be4c8
Age: 0
```

The `Age` is 0, which make sense, because it is the first time that I called this route.
If i make a second call of the same route, the `Age` header has increased, so the content has been clearly cached.

2. I make a change in my database in order to make the `api_abilities` response invalid/stale.
So, I run the following command : `bin/console fos:httpcache:invalidate:tag abilities`, the verbose output is : 

```
Sent 1 invalidation request(s)
```
3. I make a new call to `api_abilities`.

**What I expect :** a response with fresh data

**What I got :** the same data as the previous request so the date is still the same as above, and the age didn't reset to 0.

```http
Server: nginx/1.21.4
Content-Type: application/json
Content-Length: 89512
Connection: keep-alive
X-Powered-By: PHP/7.4.33
Set-Cookie: XDEBUG_SESSION=PHPSTORM; path=/; SameSite=Lax
Cache-Control: public, s-maxage=2629800
date: Fri, 01 Sep 2023 16:14:18 GMT
x-cache-debug: 1
x-cache-tags: abilities
x-content-digest: en74cdf57df9307601a67fad384500a6fc3b1dd4be3a3f56ad1f7d74b2212be4c8
Age: 478
```

Am I missing something ?

_Originally posted by @ii02735 in https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/issues/501#issuecomment-1703015451_
