### ISSUE TITLE
Allow override of request cache headers

### ISSUE THREAD

**Issue by gonzalovilaseca** [FriendsOfSymfony/FOSHttpCacheBundle#99]
In our app we'd like to control all http caching using FOSHttpCache, we've found that some bundles add default cache headers that we would like to override.
It would be nice to have a global setting like:
```
force_header_overwrite: true | false
```
Or even a way of overriding just for one rule:
```
fos_http_cache:
    cache_control:
        rules:
            # only match login.example.com
            -
                match:
                    host: ^login.example.com$
                headers:
                    cache_control: { public: false, max_age: 0, s_maxage: 0, last_modified: "-1 hour" }
                    vary: [Accept-Encoding, Accept-Language]
                    force_overwrite: true | false
```
If this is something that is useful to the community I can implement it and do a PR.
